-- Create prompts table to store AI art prompts generated by characters
-- This links to character_files to track which character generated each prompt
create table if not exists prompts (
    id uuid primary key default gen_random_uuid(),
    text text not null,
    character_id uuid references character_files(id),  -- Links to your existing character_files table
    created_at timestamp with time zone default now()
);

-- Create images table to store generated AI art and metadata
-- This links to prompts to track which prompt generated each image
create table if not exists images (
    id uuid primary key default gen_random_uuid(),
    prompt_id uuid references prompts(id),
    api_used text not null,
    image_url text not null,
    local_path text,
    settings jsonb not null,
    created_at timestamp with time zone default now()
);

-- Add indexes for better query performance
create index if not exists idx_prompts_character_id on prompts(character_id);
create index if not exists idx_images_prompt_id on images(prompt_id);

-- Add comments for documentation
comment on table prompts is 'Stores AI art prompts generated by characters from character_files';
comment on table images is 'Stores generated AI art images and their metadata';

comment on column prompts.text is 'The actual prompt text used for image generation';
comment on column prompts.character_id is 'Reference to the character in character_files that generated this prompt';
comment on column prompts.created_at is 'Timestamp when the prompt was created';

comment on column images.prompt_id is 'Reference to the prompt used to generate this image';
comment on column images.api_used is 'The AI art API used (e.g., dall-e-3)';
comment on column images.image_url is 'URL of the generated image';
comment on column images.local_path is 'Local file path where the image is stored';
comment on column images.settings is 'JSON object containing generation settings (size, quality, etc.)';
comment on column images.created_at is 'Timestamp when the image was generated'; 