version: '3.8'

services:
  marvin-art:
    build:
      context: ./Marvin-Art
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./Marvin-Art:/app
    command: /bin/bash
    tty: true
    stdin_open: true
